apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-sample
  template:
    metadata:
      labels:
        app: node-js-sample
    spec:
      containers:
        - name: node-js-sample
          image: your-image:latest
          ports:
            - containerPort: 5000
          command: ["node"]
          args: ["index.js"]
          workingDir: /usr/src/app
          env:
            - name: APP_PORT
              value: "5000"
            - name: API_KEY
              value: "secret-key" 