apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-js-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-js-sample
  template:
    metadata:
      labels:
        app: node-js-sample
    spec:
      containers:
        - name: node-js-sample
          image: image-registry.openshift-image-registry.svc:5000/th3rshifter-dev/node-nginx-sample
          ports:
            - containerPort: 80